-- Disable RLS on all tables for testing
ALTER TABLE public.departments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.positions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.employment_contracts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_postings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.applicants DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_applications DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.interview_schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.applicant_documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.onboarding_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_onboarding DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.training_programs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_trainings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.performance_evaluations DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.performance_criteria DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.evaluation_scores DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.payroll_periods DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.payroll_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.benefits DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_benefits DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs DISABLE ROW LEVEL SECURITY;

-- Drop all RLS policies
DROP POLICY IF EXISTS "Users can view own roles" ON public.user_roles;
DROP POLICY IF EXISTS "System admins can manage all roles" ON public.user_roles;
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
DROP POLICY IF EXISTS "Admins can view all profiles" ON public.profiles;
DROP POLICY IF EXISTS "Authenticated users can view departments" ON public.departments;
DROP POLICY IF EXISTS "Admins can manage departments" ON public.departments;
DROP POLICY IF EXISTS "Authenticated users can view positions" ON public.positions;
DROP POLICY IF EXISTS "Admins can manage positions" ON public.positions;
DROP POLICY IF EXISTS "Employees can view own record" ON public.employees;
DROP POLICY IF EXISTS "HR and Admins can view all employees" ON public.employees;
DROP POLICY IF EXISTS "HR and Admins can manage employees" ON public.employees;
DROP POLICY IF EXISTS "Employees can view own contracts" ON public.employment_contracts;
DROP POLICY IF EXISTS "HR and Admins can manage contracts" ON public.employment_contracts;
DROP POLICY IF EXISTS "Everyone can view active job postings" ON public.job_postings;
DROP POLICY IF EXISTS "HR can manage job postings" ON public.job_postings;
DROP POLICY IF EXISTS "Applicants can view own record" ON public.applicants;
DROP POLICY IF EXISTS "Applicants can manage own record" ON public.applicants;
DROP POLICY IF EXISTS "HR can view all applicants" ON public.applicants;
DROP POLICY IF EXISTS "Applicants can view own applications" ON public.job_applications;
DROP POLICY IF EXISTS "Applicants can create applications" ON public.job_applications;
DROP POLICY IF EXISTS "HR can manage all applications" ON public.job_applications;
DROP POLICY IF EXISTS "Applicants can view own interviews" ON public.interview_schedules;
DROP POLICY IF EXISTS "HR can manage interviews" ON public.interview_schedules;
DROP POLICY IF EXISTS "Applicants can manage own documents" ON public.applicant_documents;
DROP POLICY IF EXISTS "HR can view applicant documents" ON public.applicant_documents;
DROP POLICY IF EXISTS "View onboarding tasks" ON public.onboarding_tasks;
DROP POLICY IF EXISTS "Admins manage onboarding tasks" ON public.onboarding_tasks;
DROP POLICY IF EXISTS "Employees view own onboarding" ON public.employee_onboarding;
DROP POLICY IF EXISTS "HR manages employee onboarding" ON public.employee_onboarding;
DROP POLICY IF EXISTS "View training programs" ON public.training_programs;
DROP POLICY IF EXISTS "HR manages training programs" ON public.training_programs;
DROP POLICY IF EXISTS "Employees view own trainings" ON public.employee_trainings;
DROP POLICY IF EXISTS "HR manages employee trainings" ON public.employee_trainings;
DROP POLICY IF EXISTS "Employees view own evaluations" ON public.performance_evaluations;
DROP POLICY IF EXISTS "HR manages evaluations" ON public.performance_evaluations;
DROP POLICY IF EXISTS "View performance criteria" ON public.performance_criteria;
DROP POLICY IF EXISTS "Admins manage criteria" ON public.performance_criteria;
DROP POLICY IF EXISTS "Employees view own scores" ON public.evaluation_scores;
DROP POLICY IF EXISTS "HR manages scores" ON public.evaluation_scores;
DROP POLICY IF EXISTS "View payroll periods" ON public.payroll_periods;
DROP POLICY IF EXISTS "HR manages payroll periods" ON public.payroll_periods;
DROP POLICY IF EXISTS "Employees view own payroll" ON public.payroll_records;
DROP POLICY IF EXISTS "HR manages payroll" ON public.payroll_records;
DROP POLICY IF EXISTS "View benefits" ON public.benefits;
DROP POLICY IF EXISTS "HR manages benefits" ON public.benefits;
DROP POLICY IF EXISTS "Employees view own benefits" ON public.employee_benefits;
DROP POLICY IF EXISTS "HR manages employee benefits" ON public.employee_benefits;
DROP POLICY IF EXISTS "Employees view own documents" ON public.employee_documents;
DROP POLICY IF EXISTS "HR manages employee documents" ON public.employee_documents;
DROP POLICY IF EXISTS "Admins view audit logs" ON public.audit_logs;
DROP POLICY IF EXISTS "Authenticated users can insert audit logs" ON public.audit_logs;